# Generated by Django 3.2.4 on 2024-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../book_nook/default_profile_vdspgb', upload_to='images/'),
        ),
    ]
