# Generated by Django 3.2.4 on 2024-10-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='book description'),
        ),
        migrations.AddField(
            model_name='book',
            name='star_rating_1',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='book',
            name='star_rating_2',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='book',
            name='star_rating_3',
            field=models.IntegerField(default='3'),
        ),
        migrations.AddField(
            model_name='book',
            name='star_rating_4',
            field=models.IntegerField(default='4'),
        ),
        migrations.AddField(
            model_name='book',
            name='star_rating_5',
            field=models.IntegerField(default='5'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='books.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='books.Genre'),
        ),
    ]
