# Generated by Django 3.2.4 on 2024-05-22 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_alter_review_image'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='review',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.review'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'review')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='book',
        ),
    ]
