# Generated by Django 3.2.4 on 2024-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='../book_nook/default_post_acvybp', upload_to='images/'),
        ),
    ]
